// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/"
type AppRouteHandlerRoutes = "/api/agent" | "/api/audit" | "/api/audit/event" | "/api/catalog/categories" | "/api/catalog/compare" | "/api/catalog/products/[id]" | "/api/catalog/products/[id]/complementary" | "/api/catalog/products/[id]/image" | "/api/catalog/search" | "/api/dashboard" | "/api/orders" | "/api/orders/[id]/approve" | "/api/orders/[id]/checkout-opened" | "/api/orders/[id]/pay" | "/api/orders/[id]/payment-failed" | "/api/orders/[id]/verify-payment" | "/api/webhooks/razorpay"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/agent": {}
  "/api/audit": {}
  "/api/audit/event": {}
  "/api/catalog/categories": {}
  "/api/catalog/compare": {}
  "/api/catalog/products/[id]": { "id": string; }
  "/api/catalog/products/[id]/complementary": { "id": string; }
  "/api/catalog/products/[id]/image": { "id": string; }
  "/api/catalog/search": {}
  "/api/dashboard": {}
  "/api/orders": {}
  "/api/orders/[id]/approve": { "id": string; }
  "/api/orders/[id]/checkout-opened": { "id": string; }
  "/api/orders/[id]/pay": { "id": string; }
  "/api/orders/[id]/payment-failed": { "id": string; }
  "/api/orders/[id]/verify-payment": { "id": string; }
  "/api/webhooks/razorpay": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
