import { createHash, createHmac, timingSafeEqual } from "crypto";
import { db } from "./db";
import { audit } from "./audit";
const limit=Number(process.env.MAX_TRANSACTION_AMOUNT||10000), key=()=>process.env.RAZORPAY_KEY_ID, secret=()=>process.env.RAZORPAY_KEY_SECRET, publicKey=()=>process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID;
const equal=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
export const toPaise=(amount:number)=>Math.round(amount*100);
async function trustedOrder(id:string,sessionId:string){const o=await db.order.findUnique({where:{id},include:{product:true}});if(!o||o.sessionId!==sessionId)throw new Error("Order not found.");const u=o.upsellProductId?await db.product.findUnique({where:{id:o.upsellProductId}}):null;const expected=o.product.price+(u?.price||0);if(o.totalAmount!==expected||o.totalAmount>limit||o.product.stockStatus!=="AVAILABLE"||(u&&u.stockStatus!=="AVAILABLE"))throw new Error("Trusted order validation failed.");return {...o,upsell:u}}
export async function proposeOrder(productId:string,sessionId:string,idempotencyKey:string,upsellProductId?:string){const p=await db.product.findUnique({where:{id:productId}}),u=upsellProductId?await db.product.findUnique({where:{id:upsellProductId}}):null;if(!p||!(!upsellProductId||u)||u?.id===p.id)throw new Error("Product was not found in the trusted catalog.");if(p.stockStatus!=="AVAILABLE"||u?.stockStatus==="UNAVAILABLE")throw new Error("Product is not currently available.");const total=p.price+(u?.price||0);if(total>limit)throw new Error(`Spending policy prevents purchases above ₹${limit}.`);const existing=await db.order.findUnique({where:{idempotencyKey}});if(existing)return existing;const o=await db.order.create({data:{sessionId,productId,upsellProductId,upsellUnitPrice:u?.price,unitPrice:p.price,totalAmount:total,idempotencyKey}});await audit(sessionId,"PURCHASE_PROPOSAL_CREATED",`Purchase proposal created for ${p.title}`,true,o.id,{amount:total,upsellProductId});await audit(sessionId,"POLICY_CHECK_PASSED","Server price, availability, and spending policy passed.",true,o.id,{total,limit});return o}
export async function approveOrder(id:string,sessionId:string){const o=await trustedOrder(id,sessionId);if(o.status!=="PENDING_APPROVAL")throw new Error("This order is not awaiting approval.");const updated=await db.order.update({where:{id},data:{status:"APPROVED",approvedAt:new Date()}});await audit(sessionId,"USER_APPROVED",`User approved ₹${o.totalAmount} payment`,true,id,{policyLimit:limit});return updated}
export async function createPayment(id:string,sessionId:string,simulateFailure=false){const o=await trustedOrder(id,sessionId);if(o.status==="PAID"){await audit(sessionId,"DUPLICATE_PAYMENT_PREVENTED","Already-paid order returned without another charge.",true,o.id);return {order:o,alreadyPaid:true,mode:o.razorpayOrderId?"razorpay":"demo"}}if(simulateFailure){if(!["APPROVED","PAYMENT_CREATED","PAYMENT_PROCESSING"].includes(o.status))throw new Error("Payment is not ready to fail.");const failed=await db.order.update({where:{id:o.id},data:{status:"PAYMENT_FAILED",retryCount:{increment:1}}});await audit(sessionId,"PAYMENT_FAILED","Simulated payment failure; no successful charge was recorded.",false,o.id);return {order:failed,simulated:true,mode:"demo"}}if(!["APPROVED","PAYMENT_FAILED","PAYMENT_CREATED","PAYMENT_PROCESSING"].includes(o.status))throw new Error("Explicit approval is required before payment.");if(o.status==="PAYMENT_FAILED"&&o.retryCount>=1)throw new Error("The single permitted payment retry has already been used.");
if(key()&&secret()&&publicKey()){if(o.razorpayOrderId){const updated=await db.order.update({where:{id:o.id},data:{status:"PAYMENT_PROCESSING"}});await audit(sessionId,"DUPLICATE_PAYMENT_PREVENTED","Reusing Razorpay test order; no duplicate created.",true,o.id,{razorpayOrderId:o.razorpayOrderId});return {order:updated,mode:"razorpay",checkout:{key:publicKey(),orderId:o.razorpayOrderId,amount:toPaise(o.totalAmount),currency:o.currency,name:"AgentBuy Demo Merchant",description:o.product.title}}}try{const Razorpay=(await import("razorpay")).default;const rp=new Razorpay({key_id:key()!,key_secret:secret()!});const r=await rp.orders.create({amount:toPaise(o.totalAmount),currency:o.currency,receipt:o.id,notes:{internal_order_id:o.id,environment:"test"}});const updated=await db.order.update({where:{id:o.id},data:{status:"PAYMENT_CREATED",razorpayOrderId:r.id}});await audit(sessionId,"PAYMENT_ORDER_CREATED","Razorpay test order created from trusted server amount",true,o.id,{razorpayOrderId:r.id,amountPaise:toPaise(o.totalAmount)});return {order:updated,mode:"razorpay",checkout:{key:publicKey(),orderId:r.id,amount:toPaise(o.totalAmount),currency:o.currency,name:"AgentBuy Demo Merchant",description:o.product.title}}}catch{await audit(sessionId,"PAYMENT_FAILED","Razorpay test order could not be created.",false,o.id);throw new Error("Unable to create a Razorpay test order. Please try again.")}}
const paid=await db.order.update({where:{id:o.id},data:{status:"PAID",razorpayPaymentId:`demo_${o.id}`}});await audit(sessionId,"PAYMENT_SUCCESS","Demo-mode payment completed",true,o.id);return {order:paid,demo:true,mode:"demo"}}
export async function checkoutOpened(id:string,sessionId:string){const o=await trustedOrder(id,sessionId);if(!o.razorpayOrderId)throw new Error("Razorpay order is unavailable.");const updated=await db.order.update({where:{id:o.id},data:{status:"PAYMENT_PROCESSING"}});await audit(sessionId,"CHECKOUT_OPENED","Razorpay Test Mode Checkout opened.",true,o.id,{razorpayOrderId:o.razorpayOrderId});return updated}
export function verifySignature(orderId:string,paymentId:string,signature:string){const s=secret();return !!s&&equal(createHmac("sha256",s).update(`${orderId}|${paymentId}`).digest("hex"),signature)}
export async function verifyPayment(id:string,sessionId:string,r:{razorpay_payment_id:string;razorpay_order_id:string;razorpay_signature:string}){const o=await trustedOrder(id,sessionId);if(o.status==="PAID"){await audit(sessionId,"DUPLICATE_PAYMENT_PREVENTED","Repeated payment verification ignored.",true,o.id,{paymentId:r.razorpay_payment_id});return o}if(!o.razorpayOrderId||o.razorpayOrderId!==r.razorpay_order_id){await audit(sessionId,"PAYMENT_SIGNATURE_INVALID","Razorpay order ID did not match trusted order.",false,o.id);throw new Error("Payment order validation failed.")}if(!["PAYMENT_CREATED","PAYMENT_PROCESSING"].includes(o.status))throw new Error("Order is not awaiting payment verification.");await audit(sessionId,"PAYMENT_SUCCESS_CALLBACK","Checkout success callback received; verifying signature.",true,o.id,{paymentId:r.razorpay_payment_id});if(!verifySignature(r.razorpay_order_id,r.razorpay_payment_id,r.razorpay_signature)){await db.order.update({where:{id:o.id},data:{status:"PAYMENT_FAILED"}});await audit(sessionId,"PAYMENT_SIGNATURE_INVALID","Razorpay payment signature was invalid.",false,o.id);throw new Error("Payment verification failed. No successful payment was recorded.")}const paid=await db.order.update({where:{id:o.id},data:{status:"PAID",razorpayPaymentId:r.razorpay_payment_id}});await audit(sessionId,"PAYMENT_SIGNATURE_VERIFIED","Razorpay payment signature verified.",true,o.id,{paymentId:r.razorpay_payment_id});await audit(sessionId,"ORDER_MARKED_PAID","Order marked paid after signature verification.",true,o.id);return paid}
export async function recordPaymentFailure(id:string,sessionId:string){const o=await trustedOrder(id,sessionId);if(o.status==="PAID")return o;const failed=await db.order.update({where:{id:o.id},data:{status:"PAYMENT_FAILED",retryCount:{increment:1}}});await audit(sessionId,"PAYMENT_FAILED","Razorpay Checkout reported an unsuccessful payment.",false,o.id);return failed}
export const verifyWebhookSignature=(body:string,sig:string)=>{const s=process.env.RAZORPAY_WEBHOOK_SECRET;return !!s&&equal(createHmac("sha256",s).update(body).digest("hex"),sig)};export const webhookEventId=(body:string,header?:string|null)=>header||createHash("sha256").update(body).digest("hex");
