// Local SQLite bootstrap avoids platform-specific Prisma schema-engine failures.
// Prisma Client remains the data-access layer and this schema mirrors prisma/schema.prisma.
import { DatabaseSync } from "node:sqlite";import path from "node:path";import fs from "node:fs";
const filename=path.join(process.cwd(),"prisma","dev.db");fs.mkdirSync(path.dirname(filename),{recursive:true});const db=new DatabaseSync(filename);
db.exec(`PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS "Product" ("id" TEXT NOT NULL PRIMARY KEY,"sourceUniqueId" TEXT NOT NULL UNIQUE,"crawlTimestamp" DATETIME,"category" TEXT NOT NULL,"normalizedCategory" TEXT NOT NULL,"title" TEXT NOT NULL,"normalizedTitle" TEXT NOT NULL,"description" TEXT NOT NULL,"brand" TEXT NOT NULL,"normalizedBrand" TEXT NOT NULL,"packSize" TEXT,"mrp" REAL NOT NULL,"price" REAL NOT NULL,"offers" TEXT,"stockAvailability" TEXT NOT NULL,"stockStatus" TEXT NOT NULL,"asin" TEXT,"imageUrls" TEXT,"sellerCount" INTEGER NOT NULL DEFAULT 0,"discountPercentage" REAL NOT NULL DEFAULT 0,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL);
CREATE INDEX IF NOT EXISTS "Product_normalizedCategory_normalizedBrand_price_idx" ON "Product"("normalizedCategory","normalizedBrand","price");
CREATE TABLE IF NOT EXISTS "ProductImageCache" ("id" TEXT NOT NULL PRIMARY KEY,"productId" TEXT NOT NULL UNIQUE,"imageUrl" TEXT NOT NULL,"source" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,FOREIGN KEY("productId") REFERENCES "Product"("id") ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS "Order" ("id" TEXT NOT NULL PRIMARY KEY,"sessionId" TEXT NOT NULL,"productId" TEXT NOT NULL,"upsellProductId" TEXT,"upsellUnitPrice" REAL,"quantity" INTEGER NOT NULL DEFAULT 1,"unitPrice" REAL NOT NULL,"totalAmount" REAL NOT NULL,"currency" TEXT NOT NULL DEFAULT 'INR',"status" TEXT NOT NULL DEFAULT 'PENDING_APPROVAL',"idempotencyKey" TEXT NOT NULL UNIQUE,"razorpayOrderId" TEXT UNIQUE,"razorpayPaymentId" TEXT UNIQUE,"retryCount" INTEGER NOT NULL DEFAULT 0,"approvedAt" DATETIME,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" DATETIME NOT NULL,FOREIGN KEY("productId") REFERENCES "Product"("id"));
CREATE TABLE IF NOT EXISTS "AuditLog" ("id" TEXT NOT NULL PRIMARY KEY,"timestamp" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,"eventType" TEXT NOT NULL,"sessionId" TEXT NOT NULL,"transactionId" TEXT,"description" TEXT NOT NULL,"metadata" TEXT NOT NULL,"success" BOOLEAN NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY("transactionId") REFERENCES "Order"("id") ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS "AuditLog_sessionId_timestamp_idx" ON "AuditLog"("sessionId","timestamp");
CREATE TABLE IF NOT EXISTS "WebhookEvent" ("id" TEXT NOT NULL PRIMARY KEY,"eventId" TEXT NOT NULL UNIQUE,"eventType" TEXT NOT NULL,"createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);`);for(const sql of ['ALTER TABLE "Order" ADD COLUMN "upsellProductId" TEXT','ALTER TABLE "Order" ADD COLUMN "upsellUnitPrice" REAL'])try{db.exec(sql)}catch{ /* existing SQLite column */ }db.close();console.log(`SQLite schema ready: ${filename}`);
